version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: devops-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devops_test
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: nextjs-app
    working_dir: /app
   ## volumes:
   ##   - .:/app
   ##   - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
      MYSQL_DATABASE_NAME: devops_test
      MYSQL_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
